# Coleccion de sufijos utilizados para la lematizacion
sufijos = {

    "rtes"      : "rto",        "gancia"    : "gante",      "nadero"    : "n", 
    "cal"       : "a",          "rancia"    : "rar",        "ladero"    : "lado", 
    "ral"       : "a",          "nancia"    : "nar",        "oviene"    : "ovenir",
    "dial"      : "do",         "lancia"    : "lar",        "irida"     : "ir",         
    "bal"       : "bo",         "as"        : "a",          "madamente" : "mar",
    "onal"      : "on",         "cario"     : "ca",         "asiva"     : "asivo",
    "bral"      : "bro",        "etaria"    : "etario",     "ionada"    : "ionar",
    "ntal"      : "nto",        "onario"    : "onar",       "temente"   : "te",
    "nsual"     : "s",          "os"        : "o",          "onó"       : "onar",
    "cipal"     : "cipio",      "sario"     : "sa",         "ección"    : "ectar",
    "tinario"   : "tina",       "sora"      : "sor",        "rición"    : "recer",
    "itario"    : "idad",       "dor"       : "r",          "nación"    : "nar",
    "viario"    : "via",        "dora"      : "r",          "necen"     : "necer",
    "tario"     : "da",         "rería"     : "ro",         "zado"      : "zar",
    "nario"     : "n",          "adería"    : "ado",        "lógico"    : "logía",
    "bilidad"   : "ble",        "icería"    : "e",          "cado"      : "car",
    "íble"      : "er",         "tería"     : "to",         "vada"      : "var",
    "uible"     : "uir",        "lería"     : "l",          "ies"       : "ie",
    "able"      : "ar",         "uería"     : "a",          "dades"     : "dad",
    "ible"      : "ir",         "brero"     : "bro",        "dría"      : "der",
    "bado"      : "bar",        "ctan"      : "ctar",       "ales"      : "al",
    "iona"      : "ionar",      "eden"      : "ede",        "eves"      : "eve",
    "ienen"     : "ener",       "torio"     : "r",          "ueron"     : "ue",
    "tado"      : "tar",        "squero"    : "sca",        "cido"      : "cer",
    "nadamente" : "nar",        "ntífica"   : "ncia",       "dique"     : "dicar",
    "jeres"     : "jer",        "zada"      : "zar",        "derla"     : "der",
    "dirla"     : "dir",        "íficamente": "ificar",     "edero"     : "edar",
    "crito"     : "cribir",     "smisión"   : "smitir",     "rmó"       : "rmar",
    "bación"    : "bar",        "caría"     : "car",        "icada"     : "icar",
    "minado"    : "minar",      "erán"      : "er",         "erse"      : "er",
    "tes"       : "te",         "minadores" : "minar",      "riales"    : "ria",
    "irme"      : "irmar",      "acción"    : "actuar",     "íses"      : "ís",
    "tada"      : "tar",        "ura"       : "uro",        "mación"    : "mar",
    "cimiento"  : "cer",        "bución"    : "buir",       "ciones"    : "ctar",
    "sulado"    : "sular",      "usado"     : "usar",       "cionada"   : "cionar",
    "ientes"    : "iente",      "rvaron"    : "rvar",       "erá"       : "er",
    "yores"     : "yor",        "tita"      : "ta",         "sidad"     : "sa",
    "nientes"   : "nir",        "ctada"     : "ctar",       "tirá"      : "tir",
    "idado"     : "idar",       "juntamente": "junto",      "lada"      : "lar",
    "cialmente" : "cial",       "asan"      : "asar",       "izada"     : "izar",
    "choso"     : "char",       "trado"     : "trar",       "rvó"       : "rvar",
    "drían"     : "der",        "tores"     : "tor",        "nción"     : "nir",
    "ración"    : "rar",        "sistida"   : "sistir",     "teres"     : "ter",
    "tilación"  : "tilar",      "dación"    : "dar",        "mienda"    : "mendar",
    "tación"    : "tar",        "iste"      : "istir",      "drán"      : "der",
    "stico"     : "sticar",     "lmente"    : "l",          "ridad"     : "ro",
    "medad"     : "mo",         "gación"    : "gar",        "psulado"   : "psular",
    "mera"      : "mer",        "tima"      : "timo",       "nidad"     : "no",
    "isten"     : "istir",      "lado"      : "lar",        "uado"      : "uar",
    "seen"      : "seer",       "mado"      : "mar",        "emisión"   : "emitir",
    "uido"      : "uir",        "visión"    : "visar",      "raves"     : "rave",
    "miento"    : "r",          "ibles"     : "ible",       "cánica"    : "cánico",
    "onen"      : "oner",       "irmado"    : "irmar",      "sada"      : "sar",
    "gares"     : "gar",        "culares"   : "cular",      "tuante"    : "tuar", 
    "sentan"    : "sentar",     "nución"    : "nuir",       "nido"      : "ner",
    "ando"      : "ar",         "ió"        : "ir",         "ciente"    : "cer",
    "tares"     : "tar",        "bieron"    : "bir",        "valen"     : "valar",
    "table"     : "tabilidad",  "liares"    : "lia",        "nológico"  : "ne",
    "sivamente" : "sivo",       "oso"       : "ar",         "rativo"    : "rar",
    "rre"       : "rrir",       "tensión"   : "tenso",      "rdíaca"    : "rdíaco",
    "monares"   : "monar",      "ratoria"   : "rar",        "ginada"    : "ginar", 
    "cultad"    : "cil",        "rresponde" : "rresponder", "soles"     : "sol",
    "ducido"    : "ducir",      "ticada"    : "ticar",      "pado"      : "po",   
    "sionan"    : "sionar",     "ican"      : "icar",       "nforma"    : "nformar",
    "lores"     : "lor",        "rtado"     : "rtar",       "afía"      : "afiar",
    "aminado"   : "aminar",     "cesores"   : "cesor",      "lmonar"    : "lmón",
    "icaron"    : "icar",       "arecen"    : "arecer",     "veniente"  : "venir",
    "formes"    : "forme",      "crito"     : "cribir",     "uentran"   : "ontrar",
    "tuyen"     : "tuir",       "tran"      : "tra",        "fectivo"   : "fectar",
    "razada"    : "razar",      "llecido"   : "llecer",     "pensables" : "pensable"


} # End diccionario sufijos


# Coleccion de palabras stop utilizadas para la lematizacion
stopwords = {

    "de",       "que",      "el",       "la",       "los",      "las",      "un", 
    "uno",      "unos",     "una",      "unas",     "alguno",   "algunos",  "alguna",
    "algunas",  "a",        "se",       "del",      "por",      "con",      "no", 
    "si",       "sí",       "su",       "es",       "al",       "lo",       "como", 
    "más",      "o",        "u",        "pero",     "sus",      "suya",     "ha", 
    "me",       "sin",      "este",     "ya",       "cuando",   "todo",     "esta", 
    "ser",      "son",      "dos",      "también",  "fue",      "fué"       "había", 
    "era",      "muy",      "años",     "año",      "hasta",    "desde",    "mi", 
    "porque",   "qué",      "sólo",     "han",      "yo",       "tu",       "tú", 
    "vez",      "puede",    "todos",    "así",      "nos",      "ni",       "él", 
    "uno",      "bien",     "mal",      "ese",      "ahora",    "cada",     "e", 
    "te",       "otros",    "aunque",   "esa",      "eso",      "hace",     "otra", 
    "tan",      "día",      "ella",     "ellos",    "ella",     "ello",     "y", 
    "a",        "ante",     "bajo",     "cabe",     "con",      "contra",   "desde", 
    "durante",  "en",       "entre",    "hacia",    "hasta",    "para",     "por", 
    "según",    "sin",      "son",      "sobre",    "tras",     "gran",     "según",
    "sino",     "caso",     "nada",     "poco",     "estos",    "ante",     "unos",
    "les",      "algo",     "hacia",    "ellos",    "ayer",     "quien",    "esto",
    "están",    "está",     "esto",     "pues",     "hoy",      "otra",     "otras",
    "debe",     "cómo",     "casi",     "toda"      "tal",      "luego",    "va",
    "estas",    "sea",      "aquí",     "cual",     "he"        "aún",      "mí",
    "allí",     "allá",     "unas",     "mis",      "esos",     "dar",      "da",
    "cosa"      "sé",       "mil",      "iba",      "esas",     "ahí",      "ellas",
    "solo"      "ex",       "dio",      "etc",      "sido",     "otro",     "fue",
    "et",       "quienes",  "aún",      "fea",      "además",   "sean",     "embargo",
    "mucho",    "mismo",    "debe",     "obstante", "solo",     "via",      "diversa",
    "diverso",  "toda",     "estar",    "después",  "día",      "poco",     "puede",
    "poder",    "pueden",   "días",     "misma",    "mismas",   "mismo",    "tiene",
    "demás",    "detrás",   "fue",      "mayor",    "figura"

} # End set stopwords